[[plugins]]
repo = 'Shougo/vimproc'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'vim-scripts/The-NERD-Commenter'

[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'skanehira/translate.vim'
[[plugins]]
repo = 'yuratomo/w3m.vim'

[[plugins]]
repo = 'reireias/vim-cheatsheet'



